config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'performance_imports' => 'performance_imports#new'

  shallow do
    resources :venues do
      resources :rooms do
        resources :performances
      end
    end
  end

  shallow do
    resources :shows do
      resources :performances
    end
  end

  resources :performance_imports, only: %i[new create]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
# model for a Venue
class Venue < ApplicationRecord
  require 'csv'

  has_many :rooms, dependent: :destroy
  accepts_nested_attributes_for :rooms
  validates :name, presence: true,
                   length: { minimum: 2 },
                   uniqueness: { case_sensitive: false }

  # Class method to find a venue by name and return it
  # If no venue by that name exists it creates a new venue
  # with the passed attributes.
  def self.find_or_create(attributes = {})
    find_by(name: attributes[:name]) || Venue.create(attributes)
  end
end

app/controllers/venues_controller.rb
# controller for Venues resource
class VenuesController < ApplicationController
  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def new
    @venue = Venue.new
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue
    else
      render 'new'
    end
  end

  def update
    @venue = Venue.find(params[:id])

    if @venue.update(venue_params)
      redirect_to @venue
    else
      render 'edit'
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    redirect_to venues_path
  end

  private

  def venue_params
    params.require(:venue).permit(:name, rooms_attributes: [:id, :roomName])
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_errors.html.erb
<% if @venue.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@venue.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <%= @venue.name %>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/venues/_form.html.erb
<%= form_for @venue do |f| %>

  <%= render 'errors', object: f.object %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/venues/edit.html.erb
<h1>Edit Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>All Venues</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @venues.each do |venue| %>
    <tr>
      <td><%= venue.name %></td>
      <td><%= link_to 'Rooms and Performances', venue_path(venue) %></td>
      <td><%= link_to 'Edit Venue', edit_venue_path(venue) %></td>
      <td><%= link_to 'Delete Venue', venue_path(venue), method: :delete, data: {confirm: 'Are you sure you want to delete this Venue?' } %> </td>
    </tr>
  <% end %>


<%= link_to 'New Venue', new_venue_path %><br>


<%= link_to 'Back', welcome_index_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p>
  <h1><%= @venue.name %></h1>
  <strong>
  <%= link_to 'Add New Room', new_venue_room_path(@venue) %>

  </strong>

</p>


<%= render @venue.rooms %>


<%= link_to 'Back to all Venues', venues_path %>