config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'performance_imports' => 'performance_imports#new'

  shallow do
    resources :venues do
      resources :rooms do
        resources :performances
      end
    end
  end

  shallow do
    resources :shows do
      resources :performances
    end
  end

  resources :performance_imports, only: %i[new create]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# basic model for Rooms (sub venues) of a Venue
class Room < ApplicationRecord
  belongs_to :venue
  has_many :performances, dependent: :destroy, inverse_of: :room
  has_many :shows, through: :performances, inverse_of: :room
  validates :roomName, presence: true,
                       length: { minimum: 2 },
                       uniqueness: { case_sensitive: false }

  # Class method to find a venue by name and return it
  # If no venue by that name exists it creates a new venue
  # with the passed attributes.
  def self.find_or_create(attributes = {})
    find_by(roomName: attributes[:room_name]) ||
      Room.create_with_venue_name(attributes)
  end

  # Class method to create a new room in a venue given the venues name.
  # If no venue of that name exists a new one will be created
  def self.create_with_venue_name(attributes = {})
    venue_id = Venue.find_or_create(name: attributes[:venue_name]).id
    room_attributes = { venue_id: venue_id, roomName: attributes[:room_name] }
    Room.create(room_attributes)
  end

  # method to return the full Venue and Room name in the form Venue - Room
  def full_name
    Venue.find(venue_id).name + '-' + roomName
  end
end

app/controllers/rooms_controller.rb
# controller class for room model
class RoomsController < ApplicationController
  before_action :set_venue, only: [:index, :new, :create]

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def create
    @room = @venue.rooms.create(room_params)
    if @room.save
      redirect_to venue_path(@venue)
    else
      render 'new'
    end
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      redirect_to Venue.find(@room[:venue_id])
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @venue = Venue.find(@room[:venue_id])
    @room.destroy
    redirect_to venue_path(@venue)
  end

  private

  # method for settting venue from passed venue_id param
  # when using shallow nesting this will only work when called
  # from index, new and create
  def set_venue
    @venue = Venue.find(params[:venue_id])
  end

  def room_params
    params.require(:room).permit(:roomName)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for([@venue, @room]) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label 'Room Name:' %>
    <%= f.text_field :roomName %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rooms/_room.html.erb
<p>
  <h2><%= room.roomName %></h2>
  <%= link_to 'Edit Room', edit_room_path(room)%>
  <%= link_to 'Delete Room', [room],
  method: :delete,
  data: {confirm: "Are you sure you want to delete this room and all it's shows and performances?"}%>


</p>
<table>

  <%= render room.performances.order("date asc") %>

</table>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>
<%= link_to 'Delete Room', [@room],
method: :delete,
data: {confirm: "Are you sure you want to delete this room and all it's shows and performances?"}%>

app/views/rooms/new.html.erb
<p>
  <strong>Venue Name:</strong>
  <%= @venue.name %>
</p>


<h2>Create a New Room:</h2>
<%= render 'form' %>