config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'performance_imports' => 'performance_imports#new'

  shallow do
    resources :venues do
      resources :rooms do
        resources :performances
      end
    end
  end

  shallow do
    resources :shows do
      resources :performances
    end
  end

  resources :performance_imports, only: %i[new create]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :performances, dependent: :destroy, inverse_of: :show
  has_many :rooms, through: :performances, inverse_of: :show
  validates :title, presence: true, unless: ->(show) { show.artist.present? },
                    length: { minimum: 2 },
                    uniqueness: { scope: :artist }
  validates :artist, presence: true, unless: ->(show) { show.title.present? },
                     length: { minimum: 2 },
                     uniqueness: { scope: :title }
  validates :duration, presence: true, numericality: { only_integer: true,
                                                       greater_than: 0 }
  validates :nationality, length: { maximum: 4 }

  # method to set default show length to 1 hr if not set during initialize
  after_initialize do |show|
    show.duration ||= 60
  end

  # Class method to find a show by name and return it
  # If no show by that name exists it creates a new show
  # with the passed attributes.
  def self.find_or_create(attributes = {})
    find_by(title: attributes[:title]) || Show.create(attributes)
  end

  # method to return the nationality in brackets if it exists
  def bracketed_nationality
    return unless nationality.present?
    '(' + nationality + ')'
  end

  # method to return artist if it exists otherwise title
  def artist_or_title
    artist || title
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def new
    @show = Show.new
  end

  def edit
    @show = Show.find(params[:id])
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      redirect_to shows_path
    else
      render 'new'
    end
  end

  def update
    @show = Show.find(params[:id])

    if @show.update(show_params)

      redirect_to shows_path
    else
      render 'edit'
    end
  end

  def destroy
    @show = Show.find(params[:id])
    @show.destroy
    redirect_to shows_path
  end

  private

  def show_params
      params.require(:show).permit(:artist, :title, :duration, :nationality)
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for([@room, @show]) do |f| %>

<% if @show.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@show.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :artist%><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :duration %> (defaults to 60mins if left blank)<br>
    <%= f.number_field :duration%>
  </p>
  <p>
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shows/_show.html.erb
<tr>
  <td><b><u><%= show.artist %></u></b> <%= show.bracketed_nationality %> </td>
  <td><b><%= show.title %> - <%= show.duration %> mins </b></td>
  <td><%= link_to 'Edit Show', edit_show_path(show)%><br>
      <%= link_to 'Add Performance', new_show_performance_path(show)%></td>
  <td><%= link_to 'Delete', [show],
    method: :delete,
    data: {confirm: "Are you sure you want to delete this show and all it's  performances?"}%></td>

</tr>
<tr><%= render show.performances.order("date asc"), display_room: true %></tr>

app/views/shows/_shows.html.erb
<% @shows.each do |show| %>
  <%= render show %>
<% end %>

app/views/shows/edit.html.erb
<h1>Edit Show</h1>

<%= render 'form' %>

<%= link_to 'Back', welcome_index_path %>
<%= link_to 'Delete Show', [@show],
method: :delete,
data: {confirm: "Are you sure you want to delete this show and all it's performances?"}%>

app/views/shows/index.html.erb
<h1>All Shows</h1>
<%= link_to 'New Show', new_show_path %>

<table>
  <%= render @shows %>
</table>

<%= link_to 'Back', welcome_index_path %>

app/views/shows/new.html.erb
<h2>Create a New Show:</h2>

<%= render 'form' %>