config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'performance_imports' => 'performance_imports#new'

  shallow do
    resources :venues do
      resources :rooms do
        resources :performances
      end
    end
  end

  shallow do
    resources :shows do
      resources :performances
    end
  end

  resources :performance_imports, only: %i[new create]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :show
  belongs_to :room
  validates :date, presence: true
  validates :time, presence: true
  validates :room, presence: true
  validates :show, presence: true
  validate :cannot_overlap_another_perf

  scope :date, (->(date) { where('(date is ?)', date) })

  scope :exclude_self, (->(id) { where.not(id: id) })

  def end_time
    time + show.duration * 60
  end

  def cannot_overlap_another_perf
    return if room.blank?
    range = Range.new time, end_time
    room.performances.date(date).exclude_self(id).each do |other_perf|
      overlap_error if range.overlaps?(other_perf.time..other_perf.end_time)
    end
  end

  def overlap_error
    errors.add(:overlap_error, 'There is already an event scheduled at
                                this time and date in this room!')
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_show, only: [:index, :new, :create]

  def new
    @performance = Performance.new(room_id: 1)
  end

  def edit
    @performance = Performance.find(params[:id])
  end

  def create
    @performance = @show.performances.create(performance_params)
    if @performance.save
      redirect_to shows_path
    else
      render 'new'
    end
  end

  def update
    @performance = Performance.find(params[:id])

    if @performance.update(performance_params)
      @show = Show.find(@performance[:show_id])
      redirect_to shows_path
    else
      render 'edit'
    end
  end

  def destroy
    @performance = Performance.find(params[:id])
    @show = Show.find(@performance[:show_id])
    @performance.destroy
    redirect_to shows_path
  end

  private

  # method for settting show instance variable
  # from passed show_id param
  # when using shallow nesting this will only work when called
  # from index, new and create as only these receive this param
  def set_show
    @show = Show.find(params[:show_id])
  end

  def performance_params
      params.require(:performance).permit(:date, :time, :duration, :room_id)
  end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<%= form_for([@show, @performance]) do |f| %>

<% if @performance.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@performance.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @performance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :date%><br>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_field :time %>
  </p>
  <p>
    <%= f.label :room %><br>
    <%= f.collection_select :room_id, Room.all, :id, :full_name, prompt: true, selected: @performance.room_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/performances/_performance.html.erb
<td style="border: 1px solid black">

<%-# local variable display_room denotes whether to render the room name -%>
<%-# (by default the artist (or title if no artist) will be rendered) -%>

<% if local_assigns[:display_room] %>
  <% room = Room.find(performance.room_id) %>
  <%= Venue.find(room.venue_id).name %><br>
  <%= room.roomName %><br>
<% else %>
  <% show = Show.find(performance.show_id) %>
  <%= show.artist_or_title %><br>
<% end %>

<%= performance.date %><br>
<%= performance.time %> - <%= performance.end_time %><br>
<%= link_to 'Edit', edit_performance_path(performance)%>
<%= link_to 'Delete', [performance],
    method: :delete,
    data: {confirm: "Are you sure you want to delete this performance?"}%>
</td>

app/views/performances/edit.html.erb
<h1>Edit Performance</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>
<%= link_to 'Delete Performance', [@performance],
method: :delete,
data: {confirm: "Are you sure you want to delete this performances?"}%>

app/views/performances/new.html.erb
<p>
  <b><%= @show.artist %></b>
  <%= @show.title %>
</p>

<h2>Create a New Performance:</h2>

<%= render 'form' %>